projects:
  protocol-dev:
    schema: protocol.schema.graphql
    include: src/docs/**/*.graphql
    extensions:
      endpoints:
        Protocol:
          url: https://thegraph.azuro.org/subgraphs/name/azuro-protocol/azuro-api-mumbai-dev-v3
          headers:
            user-agent: JS GraphQL
          introspect: false
